// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuUJ6wguGi_5fIn6q48sjrUB2ViGdk7ps',
    appId: '1:561758300246:web:7768cfd0c4ad70ef8373f7',
    messagingSenderId: '561758300246',
    projectId: 'poultryvision-9ee86',
    authDomain: 'poultryvision-9ee86.firebaseapp.com',
    storageBucket: 'poultryvision-9ee86.firebasestorage.app',
    measurementId: 'G-VDWB6D7F4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcJ6X8khjKl5ruix5qNMmMRdyzlPYLiMo',
    appId: '1:561758300246:android:b92770729540151a8373f7',
    messagingSenderId: '561758300246',
    projectId: 'poultryvision-9ee86',
    storageBucket: 'poultryvision-9ee86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvYY6CIrpcZPbWkl49WtzEbDRkH8K9980',
    appId: '1:561758300246:ios:ec02a89b661cc1978373f7',
    messagingSenderId: '561758300246',
    projectId: 'poultryvision-9ee86',
    storageBucket: 'poultryvision-9ee86.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvYY6CIrpcZPbWkl49WtzEbDRkH8K9980',
    appId: '1:561758300246:ios:ec02a89b661cc1978373f7',
    messagingSenderId: '561758300246',
    projectId: 'poultryvision-9ee86',
    storageBucket: 'poultryvision-9ee86.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuUJ6wguGi_5fIn6q48sjrUB2ViGdk7ps',
    appId: '1:561758300246:web:f7ffee8a446566658373f7',
    messagingSenderId: '561758300246',
    projectId: 'poultryvision-9ee86',
    authDomain: 'poultryvision-9ee86.firebaseapp.com',
    storageBucket: 'poultryvision-9ee86.firebasestorage.app',
    measurementId: 'G-2EF2JKXGPM',
  );
}
